name: Send Images to EFS

on:
  push:
    branches:
      - "main"
      - "developer"
    paths:
      - 'images/**'

jobs:
  send-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Test AWS CLI
        run: aws sts get-caller-identity

      - name: Retrieve private key (replace with your secure storage method)
        uses: aws/aws-actions/secretsmanager-get-secret-value@v1
        with:
          name: chaveppk  # Replace with your secret name

      - name: Transfer images to EC2
        uses: gobuffalo/sftp@v1  # Example action, choose a trusted one
        with:
          host: ${{ secrets.EC2_HOST }}  # EC2 hostname or IP
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.MY_PRIVATE_KEY }}  # Replace with retrieved key secret
          remote: /efs  # Target folder on EC2
          local: $new_images
