name: Send Images to EFS

on:
  push:
    branches:
      - "main"
      - "developer"
    paths:
      - 'images/**'

jobs:
  send-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Test AWS CLI
        run: aws sts get-caller-identity

      - name: Identify new images
        id: find-images
        run: |
          new_images=$(find images -type f -name "*.png" -mtime -1 -print)
          if [ -z "$new_images" ]; then
            echo "No new images found."
            echo "::set-output name=has_new_images::false"
          else
            echo "New images: $new_images"
            echo "::set-output name=has_new_images::true"
            echo "::set-output name=new_images::$new_images"
          fi

      - name: Transfer new images to S3
        if: steps.find-images.outputs.has_new_images == 'true'
        run: |
          for image in ${new_images[@]}
          do
            aws s3 cp "$image" "s3://Decathlom/path/on/efs/$(basename "$image")"
          done
        env:
          new_images: ${{ steps.find-images.outputs.new_images }}
