name: Send Images to EFS

on:
  push:
    branches:
      - "main"
      - "developer"
    paths:
      - 'images/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install SSH dependencies
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      - name: Install SSH Key
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Copy files to EC2
        run: scp -i ~/.ssh/id_rsa -r ./images/* ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/efs
