name: Send Images to EFS

on:
  push:
    branches:
      - "main"
      - "developer"
    paths:
      - 'images/**'
      - '.github/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install SSH dependencies
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      - name: Install SSH Key
        run: |
          ssh-keygen -t rsa -b 4096 -f ~/.ssh/id_rsa -N ''
          ssh-keyscan -H 54.147.110.59 >> ~/.ssh/known_hosts

      - name: Copy files to EC2
        run: |
          echo "$CHAVE_PEM" > ./key.pem
          chmod 600 ./key.pem
          scp -i ./key.pem -r ./images/* ec2-user@54.147.110.59:/efs
        env:
          CHAVE_PEM: ${{ secrets.SSH_KEY }}
